# Generated by Django 5.2.10 on 2026-01-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.IntegerField()),
                ('ac_no', models.IntegerField()),
                ('ps_no', models.IntegerField()),
                ('sl_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('relation_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('door_no', models.CharField(max_length=50)),
                ('epic_no', models.CharField(max_length=20)),
            ],
        ),
    ]
